# fly.toml app configuration file generated for mpesa-insights on 2025-09-17T16:32:30+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mpesa-insights'
primary_region = 'fra'

[build]

[env]
  PORT = '8501'

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.http_options]
    h2_backend = true
    response.headers = { "X-Frame-Options" = "SAMEORIGIN" }

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "10s"
    path = "/_stcore/health"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
